# Generated by Django 4.1.7 on 2023-03-15 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nome'], 'verbose_name': 'Empresa'},
        ),
    ]
