# Generated by Django 4.1.7 on 2023-03-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0002_alter_empresa_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cliente',
                'db_table': 'po2_cliente',
                'ordering': ['nome'],
            },
        ),
    ]
