# Generated by Django 4.1.7 on 2023-03-15 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0005_alter_empresa_nome'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('empresa', 'nome')},
        ),
    ]
