# Generated by Django 4.1.7 on 2023-03-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0007_bordado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bordado',
            unique_together={('cliente', 'nome')},
        ),
        migrations.RemoveField(
            model_name='bordado',
            name='empresa',
        ),
    ]
