# Generated by Django 4.1.7 on 2023-04-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0010_delete_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DificuldadeBordado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(unique=True)),
                ('descricao', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Dificuldade de bordado',
                'verbose_name_plural': 'Dificuldades de bordado',
                'db_table': 'po2_dificuldade_bordado',
                'ordering': ['ordem'],
            },
        ),
    ]
