# Generated by Django 4.1.7 on 2023-04-09 20:37

from django.db import migrations, models


def do(apps, schema_editor):
    DificuldadeBordado = apps.get_model("bordado", "DificuldadeBordado")
    db = DificuldadeBordado(
        ordem=0,
        descricao="Indefinida",
    )
    db.save()


def undo(apps, schema_editor):
    DificuldadeBordado = apps.get_model("bordado", "DificuldadeBordado")
    DificuldadeBordado.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0013_alter_bordado_tamanho_maximo'),
    ]

    operations = [
        migrations.RunPython(do, undo),
    ]
