# Generated by Django 4.1.7 on 2023-04-09 20:54

import bordado.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0014_insert_dificuldadebordado'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordado',
            name='dificuldade',
            field=models.ForeignKey(default=bordado.models.DificuldadeBordado.id_indefinida, on_delete=django.db.models.deletion.PROTECT, to='bordado.dificuldadebordado'),
        ),
    ]
