# Generated by Django 4.1.7 on 2023-04-13 14:04

from django.db import migrations, models


def cnpj9_unique_value(apps, schema_editor):
    Cliente = apps.get_model('bordado', 'Cliente')
    for o in Cliente.objects.all():
        o.cnpj9 = o.id
        o.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0015_bordado_dificuldade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cnpj2',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='cnpj4',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='cnpj9',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(cnpj9_unique_value),
    ]
