# Generated by Django 4.1.7 on 2023-04-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0016_cliente_cnpj2_cliente_cnpj4_cliente_cnpj9'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('cnpj9', 'cnpj4', 'cnpj2')},
        ),
    ]
