# Generated by Django 4.1.7 on 2023-04-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0017_alter_cliente_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj2',
            field=models.PositiveSmallIntegerField(verbose_name='CNPJ (dígitos)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj4',
            field=models.PositiveSmallIntegerField(verbose_name='CNPJ (filial)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj9',
            field=models.PositiveIntegerField(verbose_name='CNPJ (raiz)'),
        ),
    ]
