# Generated by Django 4.1.7 on 2023-04-13 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0018_alter_cliente_cnpj2_alter_cliente_cnpj4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj2',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='CNPJ (dígitos)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj4',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='CNPJ (filial)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj9',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)], verbose_name='CNPJ (raiz)'),
        ),
    ]
