# Generated by Django 4.1.7 on 2023-04-13 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0019_alter_cliente_cnpj2_alter_cliente_cnpj4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='boleto',
            field=models.BooleanField(default=False, verbose_name='Gera boleto?'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='conta_corrente',
            field=models.BooleanField(default=False, verbose_name='Trabalha como conta corrente?'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='parcela',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Número de parcelas padrão'),
        ),
    ]
