# Generated by Django 4.1.7 on 2023-04-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0020_cliente_boleto_cliente_conta_corrente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False, verbose_name='Número')),
            ],
            options={
                'verbose_name': 'Ordem de produção',
                'verbose_name_plural': 'Ordens de produção',
                'db_table': 'po2_op',
            },
        ),
    ]
