# Generated by Django 4.1.7 on 2023-04-13 18:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0021_ordemproducao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemproducao',
            options={'ordering': ['numero'], 'verbose_name': 'Ordem de produção', 'verbose_name_plural': 'Ordens de produção'},
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='bordado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='bordado.bordado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='bordado.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='inserido_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='quantidade',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
