# Generated by Django 4.1.7 on 2023-04-13 18:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0023_alter_ordemproducao_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApontamentoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_perda', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='quantidade de perda')),
                ('qtd_prod', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='quantidade produzida')),
                ('apontado_em', models.DateTimeField(auto_now_add=True)),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bordado.ordemproducao')),
            ],
            options={
                'verbose_name': 'Apontamento de produção',
                'verbose_name_plural': 'Apontamentos de produção',
                'db_table': 'po2_aponta_prod',
                'ordering': ['-op_id', 'apontado_em'],
            },
        ),
    ]
