# Generated by Django 4.1.7 on 2023-04-26 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0024_apontamentoproducao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False, verbose_name='Número')),
                ('cancelado', models.BooleanField(default=False)),
                ('inserido_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bordado.cliente')),
            ],
            options={
                'db_table': 'po2_pedido',
                'ordering': ['-numero'],
            },
        ),
    ]
