# Generated by Django 4.1.7 on 2023-04-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0025_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
