# Generated by Django 4.1.7 on 2023-04-26 18:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0026_pedido_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('inserido_em', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)], verbose_name='Preço')),
                ('cancelado', models.BooleanField(default=False)),
                ('bordado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bordado.bordado')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bordado.pedido')),
            ],
            options={
                'verbose_name': 'Item de pedido',
                'verbose_name_plural': 'Itens de pedido',
                'db_table': 'po2_pedido_item',
                'ordering': ['-pedido__numero', '-ordem'],
            },
        ),
    ]
