# Generated by Django 4.1.7 on 2023-04-26 18:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0028_remove_ordemproducao_bordado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False, verbose_name='Número')),
                ('quantidade', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('cancelado', models.BooleanField(default=False)),
                ('inserido_em', models.DateTimeField(auto_now_add=True)),
                ('pedido_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bordado.pedidoitem')),
            ],
            options={
                'verbose_name': 'Ordem de produção',
                'verbose_name_plural': 'Ordens de produção',
                'db_table': 'po2_op',
                'ordering': ['-numero'],
            },
        ),
    ]
