# Generated by Django 4.1.7 on 2023-04-09 20:37

from django.db import migrations, models


def do(apps, schema_editor):
    Cliente = apps.get_model("bordado", "Cliente")
    clientes = Cliente.objects.all()
    for cliente in clientes:
        cliente.apelido = cliente.nome
        cliente.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0032_cliente_apelido'),
    ]

    operations = [
        migrations.RunPython(do),
    ]
