# Generated by Django 4.1.7 on 2023-06-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0033_cliente_apelido_init'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apelido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
