# Generated by Django 4.1.7 on 2023-06-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0035_alter_bordado_cliente'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('cnpj9', 'cnpj4')},
        ),
    ]
