# Generated by Django 4.1.7 on 2023-06-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0036_alter_cliente_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pedidoitem',
            unique_together={('pedido', 'ordem')},
        ),
    ]
