# Generated by Django 4.1.7 on 2023-06-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0037_alter_pedidoitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pedidoitem',
            unique_together={('ordem', 'pedido')},
        ),
    ]
