# Generated by Django 4.1.7 on 2023-06-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0038_alter_pedidoitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bordado',
            unique_together={('nome', 'cliente')},
        ),
    ]
