# Generated by Django 4.1.7 on 2023-06-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0039_alter_bordado_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apontamentoproducao',
            unique_together={('apontado_em', 'op')},
        ),
    ]
