# Generated by Django 4.1.7 on 2023-06-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0041_cliente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='quando',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
