# Generated by Django 4.1.7 on 2023-09-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0042_cliente_quando'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apelido',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
