# Generated by Django 4.1.7 on 2023-09-15 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0043_alter_cliente_apelido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['apelido'], 'verbose_name': 'Cliente'},
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together=set(),
        ),
    ]
