# Generated by Django 4.1.7 on 2023-09-15 02:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0044_alter_cliente_options_alter_cliente_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj4',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='CNPJ (filial)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj9',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)], verbose_name='CNPJ (raiz)'),
        ),
    ]
