# Generated by Django 4.1.7 on 2023-09-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0046_alter_cliente_cnpj2_alter_cliente_cnpj4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
