# Generated by Django 4.1.7 on 2023-11-30 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bordado', '0048_alter_cliente_apelido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
            preserve_default=False,
        ),
    ]
