# Generated by Django 4.1.7 on 2023-12-01 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0049_pedidoitem_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1000000)], verbose_name='Preço'),
        ),
    ]
