# Generated by Django 4.1.7 on 2023-12-01 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0050_alter_pedidoitem_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='ajuste',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='programacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1000000)], verbose_name='Pogramação'),
        ),
    ]
