# Generated by Django 4.1.7 on 2023-12-02 22:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bordado', '0051_pedidoitem_ajuste_pedidoitem_programacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1000000)])),
                ('tipo', models.CharField(max_length=50)),
                ('nf', models.PositiveIntegerField(blank=True, null=True, verbose_name='NF')),
                ('data', models.DateField(blank=True, null=True)),
                ('parcelamento', models.CharField(blank=True, max_length=50, null=True)),
                ('quando', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Cobrança',
                'db_table': 'po2_cobranca',
                'ordering': ['-id'],
            },
        ),
    ]
