# Generated by Django 4.1.7 on 2023-12-02 22:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0052_cobranca'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoItemCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1000000)])),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bordado.cobranca')),
                ('pedido_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bordado.pedidoitem')),
            ],
            options={
                'verbose_name': 'Cobrança de item de pedido',
                'verbose_name_plural': 'Cobranças de itens de pedido',
                'db_table': 'po2_pedido_item_cobranca',
            },
        ),
    ]
