# Generated by Django 4.1.7 on 2023-12-02 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0053_pedidoitemcobranca'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranca',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bordado.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='data',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
