# Generated by Django 4.1.7 on 2023-12-03 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0054_cobranca_cliente_alter_cobranca_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitemcobranca',
            name='pedido_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas', to='bordado.pedidoitem'),
        ),
    ]
