# Generated by Django 4.1.7 on 2023-12-03 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0055_alter_pedidoitemcobranca_pedido_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranca',
            name='tipo',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1, 'O campo Tipo deve conter ao menos um caractere.')]),
        ),
    ]
