# Generated by Django 4.1.7 on 2023-12-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0056_alter_cobranca_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranca',
            name='parcelamento',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
    ]
