# Generated by Django 4.1.7 on 2023-12-03 17:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bordado', '0057_alter_cobranca_parcelamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('informacao', models.CharField(default='0', max_length=50, verbose_name='Informação')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(-1000000), django.core.validators.MaxValueValidator(1000000)])),
                ('quando', models.DateTimeField(auto_now=True)),
                ('cobranca', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='bordado.cobranca')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Lançamento',
                'db_table': 'po2_lancamento',
            },
        ),
    ]
