# Generated by Django 4.1.7 on 2023-12-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0059_lancamento_saldo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lancamento',
            options={'ordering': ['-data', '-id'], 'verbose_name': 'Lançamento'},
        ),
    ]
