# Generated by Django 4.1.7 on 2023-12-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0060_alter_lancamento_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='informacao',
            field=models.CharField(max_length=50, verbose_name='Informação'),
        ),
    ]
