# Generated by Django 4.1.7 on 2023-12-03 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0061_alter_lancamento_informacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='cobranca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bordado.cobranca'),
        ),
    ]
