# Generated by Django 4.1.7 on 2023-12-03 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0063_rename_saldo_lancamento_saldo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='bordado.cliente'),
            preserve_default=False,
        ),
    ]
