# Generated by Django 4.1.7 on 2023-12-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0065_lancamento_saldo_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='calculando',
            field=models.BooleanField(default=False),
        ),
    ]
