# Generated by Django 4.1.7 on 2023-12-05 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordado', '0066_lancamento_calculando'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='n_parcelas',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nº de parcelas'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='parcela',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
